import React, { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useEcoTrack } from '../context/EcoTrackContext';
import { FileDown, Calendar, BarChart3, TrendingDown, Info, ShieldCheck } from 'lucide-react';
import { calculateSustainabilityScore } from '../services/emissions';

const Reports: React.FC = () => {
  const { userProfile } = useAuth();
  const { reports, activities } = useEcoTrack();
  const [downloading, setDownloading] = useState(false);
  const [selectedMonth, setSelectedMonth] = useState(() => {
    return reports[0]?.month || new Date().toISOString().substring(0, 7);
  });

  // Find active report or build one dynamically
  const activeReport = reports.find(r => r.month === selectedMonth) || (() => {
    // Generate dynamic fallback summary if no report generated by Gemini yet
    const monthlyActs = activities.filter(act => act.date.startsWith(selectedMonth));
    const breakdown = {
      transport: monthlyActs.reduce((acc, act) => acc + act.transport.emissions, 0),
      electricity: monthlyActs.reduce((acc, act) => acc + act.electricity.emissions, 0),
      food: monthlyActs.reduce((acc, act) => acc + act.food.emissions, 0),
      water: monthlyActs.reduce((acc, act) => acc + act.water.emissions, 0),
      waste: monthlyActs.reduce((acc, act) => acc + act.waste.emissions, 0)
    };
    const total = Object.values(breakdown).reduce((a, b) => a + b, 0);

    return {
      month: selectedMonth,
      emissionsBreakdown: breakdown,
      totalEmissions: Number(total.toFixed(2)),
      averageEmissions: 450,
      sustainabilityScore: calculateSustainabilityScore(total),
      aiInsights: "Please go to the Dashboard and click 'Generate Recommendations' to activate your Gemini Sustainability Coach feedback for this month."
    };
  })();

  const handleDownloadPDF = async () => {
    const reportElement = document.getElementById('report-pdf-area');
    if (!reportElement) return;

    setDownloading(true);

    try {
      // Lazy load dependencies to optimize bundle size
      const html2canvas = (await import('html2canvas')).default;
      const { jsPDF } = await import('jspdf');

      const canvas = await html2canvas(reportElement, {
        scale: 2, // Double quality
        useCORS: true,
        backgroundColor: document.body.classList.contains('dark') ? '#0b0f19' : '#f8fafc'
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const imgWidth = 210; // A4 dimensions
      const pageHeight = 295;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;

      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(`ecotrack_report_${selectedMonth}.pdf`);
    } catch (error) {
      console.error('Failed to export PDF:', error);
    } finally {
      setDownloading(false);
    }
  };

  const getSavingsPercentage = () => {
    const avg = activeReport.averageEmissions;
    const user = activeReport.totalEmissions;
    if (user >= avg) return 0;
    return Math.round(((avg - user) / avg) * 100);
  };

  const breakdownLabels = {
    transport: 'Transport Footprint',
    electricity: 'Electricity Utility',
    food: 'Dietary Habits',
    water: 'Water Usage',
    waste: 'Waste & Recycling'
  };

  return (
    <div className="space-y-6">
      
      {/* Title */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="font-outfit text-3xl font-extrabold tracking-tight">Reports & <span className="eco-gradient-text font-bold">Analytics</span></h1>
          <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">
            Download your carbon report summaries and view comparisons with average users.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {/* Month selector dropdown */}
          <div className="relative">
            <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-emerald-500" />
            <select
              value={selectedMonth}
              onChange={(e) => setSelectedMonth(e.target.value)}
              className="glass-input pl-9 pr-8 py-2 text-xs font-semibold"
            >
              {/* Generate dropdown selections based on logged reports */}
              {reports.length > 0 ? (
                reports.map(rep => (
                  <option key={rep.month} value={rep.month}>{rep.month}</option>
                ))
              ) : (
                <option value={new Date().toISOString().substring(0, 7)}>
                  {new Date().toISOString().substring(0, 7)}
                </option>
              )}
            </select>
          </div>

          <button
            onClick={handleDownloadPDF}
            disabled={downloading}
            className="px-4 py-2 bg-emerald-500 hover:bg-emerald-600 text-white rounded-xl font-bold text-xs shadow-md shadow-emerald-500/10 flex items-center gap-2 transition-all disabled:opacity-50"
          >
            {downloading ? (
              <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
            ) : (
              <FileDown className="w-4 h-4" />
            )}
            <span>{downloading ? 'Compiling PDF...' : 'Download Report'}</span>
          </button>
        </div>
      </div>

      {/* Comparative analytics section */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        
        {/* Comparison card */}
        <div className="glass-card rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-lg md:col-span-2 space-y-4">
          <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
            <BarChart3 className="w-4 h-4 text-emerald-500" />
            <span>EcoTrack Peer Benchmarking</span>
          </h3>

          <div className="space-y-4 pt-2">
            
            {/* Peer average footprint progress bar */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-semibold">
                <span className="text-slate-500">Average EcoTrack User</span>
                <span>{activeReport.averageEmissions} kg CO₂</span>
              </div>
              <div className="h-3 w-full bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                <div className="h-full bg-slate-400 dark:bg-slate-600 rounded-full" style={{ width: '100%' }}></div>
              </div>
            </div>

            {/* User footprint progress bar */}
            <div className="space-y-1.5">
              <div className="flex justify-between text-xs font-semibold">
                <span className="font-bold">Your Footprint ({selectedMonth})</span>
                <span className="text-emerald-500 font-bold">{activeReport.totalEmissions} kg CO₂</span>
              </div>
              <div className="h-3 w-full bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                <div 
                  className={`h-full rounded-full ${activeReport.totalEmissions <= activeReport.averageEmissions ? 'bg-emerald-500' : 'bg-rose-500'}`}
                  style={{ width: `${Math.min(120, (activeReport.totalEmissions / activeReport.averageEmissions) * 100)}%` }}
                ></div>
              </div>
            </div>

          </div>
        </div>

        {/* Savings metric box */}
        <div className="glass-card rounded-3xl p-6 border border-slate-200 dark:border-slate-800 shadow-lg md:col-span-1 flex flex-col justify-between items-center text-center">
          <div>
            <span className="text-xs font-bold text-slate-400 uppercase tracking-widest block">Carbon Avoided</span>
            {getSavingsPercentage() > 0 ? (
              <div className="mt-4 space-y-2">
                <div className="w-14 h-14 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-500 flex items-center justify-center mx-auto">
                  <TrendingDown className="w-7 h-7" />
                </div>
                <h4 className="font-outfit text-3xl font-extrabold text-emerald-500">-{getSavingsPercentage()}%</h4>
                <p className="text-xs text-slate-500 max-w-[160px] mx-auto leading-relaxed">
                  You are emitting less carbon than the average community footprint!
                </p>
              </div>
            ) : (
              <div className="mt-4 space-y-2">
                <div className="w-14 h-14 rounded-full bg-rose-500/10 border border-rose-500/20 text-rose-500 flex items-center justify-center mx-auto">
                  <Info className="w-7 h-7" />
                </div>
                <h4 className="font-outfit text-3xl font-extrabold text-rose-500">0% Saved</h4>
                <p className="text-xs text-slate-500 max-w-[160px] mx-auto leading-relaxed">
                  Your carbon emissions are above target. Adopt tips from the Coach panel.
                </p>
              </div>
            )}
          </div>
        </div>

      </div>

      {/* PDF Target Container */}
      <div 
        id="report-pdf-area" 
        className="p-8 md:p-12 rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-xl space-y-8 max-w-4xl mx-auto"
      >
        {/* PDF Header */}
        <div className="flex justify-between items-start border-b border-slate-150 dark:border-slate-800 pb-6">
          <div className="space-y-1">
            <h2 className="font-outfit text-2xl font-extrabold tracking-tight bg-gradient-to-r from-emerald-500 to-teal-500 bg-clip-text text-transparent">
              EcoTrack Sustainability Profile
            </h2>
            <p className="text-xs text-slate-500">Generated for user: {userProfile?.name} ({userProfile?.email})</p>
          </div>
          <div className="text-right">
            <span className="text-[10px] text-slate-400 uppercase font-bold tracking-wider block">Report Month</span>
            <span className="text-sm font-bold text-slate-700 dark:text-slate-300">{selectedMonth}</span>
          </div>
        </div>

        {/* Breakdown details */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
          <div className="space-y-4">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">Emissions Category Breakdown</h4>
            
            <div className="space-y-3">
              {Object.entries(activeReport.emissionsBreakdown).map(([key, val]) => (
                <div key={key} className="flex items-center justify-between text-sm py-1.5 border-b border-slate-100 dark:border-slate-800/50">
                  <span className="text-slate-600 dark:text-slate-400">{breakdownLabels[key as keyof typeof breakdownLabels]}</span>
                  <span className="font-bold">{Number(val.toFixed(2))} kg CO₂</span>
                </div>
              ))}
              <div className="flex items-center justify-between text-base font-extrabold pt-3 border-t border-slate-200 dark:border-slate-800">
                <span>Total Monthly Footprint</span>
                <span className="text-emerald-500">{activeReport.totalEmissions} kg CO₂</span>
              </div>
            </div>
          </div>

          {/* User Score dial in report */}
          <div className="p-6 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-4">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest text-center">Sustainability Scorecard</h4>
            <div className="flex flex-col items-center justify-center py-4">
              <div className="w-28 h-28 rounded-full border-4 border-emerald-500/30 flex flex-col items-center justify-center bg-white dark:bg-slate-900 shadow-md">
                <span className="font-outfit text-4xl font-extrabold text-emerald-500">{activeReport.sustainabilityScore}</span>
                <span className="text-[9px] text-slate-400 uppercase font-bold">out of 100</span>
              </div>
              <p className="text-xs font-semibold text-slate-500 mt-4 text-center">
                Score indicates environmental impact. Higher means a cleaner footprint.
              </p>
            </div>
          </div>
        </div>

        {/* AI Insight report in PDF */}
        <div className="space-y-3 border-t border-slate-200 dark:border-slate-800 pt-6">
          <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest">AI Sustainability Recommendations</h4>
          <div className="text-xs text-slate-600 dark:text-slate-350 leading-relaxed bg-slate-50 dark:bg-slate-950 p-5 rounded-2xl border border-slate-200 dark:border-slate-800">
            {activeReport.aiInsights.split('\n').slice(0, 8).join('\n') || activeReport.aiInsights}
            {activeReport.aiInsights.split('\n').length > 8 && '\n... [Remaining recommendations available in app dashboard]'}
          </div>
        </div>

        {/* Verification footer seal */}
        <div className="flex justify-between items-center text-[10px] text-slate-400 border-t border-slate-100 dark:border-slate-800 pt-4">
          <div className="flex items-center gap-1">
            <ShieldCheck className="w-4 h-4 text-emerald-500" />
            <span>EcoTrack Verification System Verified</span>
          </div>
          <span>Report created on: {new Date().toLocaleDateString()}</span>
        </div>

      </div>

    </div>
  );
};

export default Reports;
